### ISSUE TITLE
1.8.0 is not installable: .../sphinx-prompt does not contain any element

### ISSUE THREAD

**Issue by mgorny** [sbrunner/sphinx-prompt#398]
```
$ python -m build -w
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (poetry-core>=1.0.0, poetry-dynamic-versioning, poetry-plugin-tweak-dependencies-version)
* Getting build dependencies for wheel...
* Building wheel...
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/usr/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-xgxeu_dd/lib/python3.12/site-packages/poetry/core/masonry/api.py", line 67, in build_wheel
    return WheelBuilder.make_in(poetry, Path(wheel_directory))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-xgxeu_dd/lib/python3.12/site-packages/poetry/core/masonry/builders/wheel.py", line 74, in make_in
    wb = WheelBuilder(
         ^^^^^^^^^^^^^
  File "/tmp/build-env-xgxeu_dd/lib/python3.12/site-packages/poetry/core/masonry/builders/wheel.py", line 57, in __init__
    super().__init__(poetry, executable=executable)
  File "/tmp/build-env-xgxeu_dd/lib/python3.12/site-packages/poetry/core/masonry/builders/builder.py", line 83, in __init__
    self._module = Module(
                   ^^^^^^^
  File "/tmp/build-env-xgxeu_dd/lib/python3.12/site-packages/poetry/core/masonry/utils/module.py", line 79, in __init__
    PackageInclude(
  File "/tmp/build-env-xgxeu_dd/lib/python3.12/site-packages/poetry/core/masonry/utils/package_include.py", line 29, in __init__
    self.check_elements()
  File "/tmp/build-env-xgxeu_dd/lib/python3.12/site-packages/poetry/core/masonry/utils/package_include.py", line 66, in check_elements
    raise ValueError(
ValueError: /tmp/sphinx-prompt-1.8.0/sphinx-prompt does not contain any element

ERROR Backend subprocess exited when trying to invoke build_wheel
```

**Comment by sbrunner** [comment]
You should run  `cp sphinx_prompt sphinx-prompt` before :-)

**Comment by jloehel** [comment]
Why is this step necessary?

**Comment by sbrunner** [comment]
To make the package available on sphinx-prompt and on sphinx_prompt for backward compatibility.
